/* eslint-disable no-undef */
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import NavBar from './pages/core/NavBar'

const Layout = ({
	title,
	children,
}: {
	title?: string
	children: JSX.Element
}) => {
	return (
		<>
			<Head>
				<title>{title ? title : 'ecomsite'}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<ToastContainer position='top-center' limit={1} />
			<div className='flex min-h-screen flex-col justify-between'>
				<header>
					<NavBar />
				</header>
				<main className='container m-auto mt-4 px-4'>{children}</main>
				<footer className='flex h-10 justify-center items-center'>
					&copy; Copyright 2022,EcomSite
				</footer>
			</div>
		</>
	)
}
export default Layout
